# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simpler-tiles}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeff Larson"]
  s.date = %q{2011-06-09}
  s.description = %q{mappy maps!}
  s.email = %q{thejefflarson@gmail.com}
  s.extensions = ["ext/simpler_tiles/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "ext/simpler_tiles/depend",
    "ext/simpler_tiles/extconf.rb",
    "ext/simpler_tiles/map.c",
    "ext/simpler_tiles/map.h",
    "ext/simpler_tiles/mkmf.log",
    "ext/simpler_tiles/simpler_tiles.c",
    "ext/simpler_tiles/simpler_tiles.h",
    "lib/simpler_tiles.rb",
    "lib/simpler_tiles/map.rb",
    "lib/simpler_tiles/mixins/pp.rb",
    "simpler-tiles.gemspec",
    "test/helper.rb",
    "test/test_map.rb",
    "test/test_simpler_tiles.rb"
  ]
  s.homepage = %q{http://github.com/thejefflarson/simpler-tiles}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{maps!}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake-compiler>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rake-compiler>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake-compiler>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

